version: '3.8'

services:
    php:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: php_prod
        image: aristote-front-php-prod
        user: "${UID:-0}:${GID:-0}"
        env_file:
            - .env.local
        environment:
            APP_ENV: prod
        depends_on:
            - postgres

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile.prod
            target: nginx
            args:
                PHP_DESTINATION: aristote-front-php-prod
        image: aristote-front-nginx-prod
        environment:
            PHP_BACKEND: php
        depends_on:
            - php
        ports:
            - "8080:80"
            - "443:443"

    postgres:
        image: postgres:15-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: aristote-front
            POSTGRES_PASSWORD: aristote-front
            POSTGRES_DB: aristote-front-db
            POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=sl-SI"
