openapi: 3.0.3
info:
  title: Swagger Aristote - OpenAPI 3.0
  version: 0.0.1
  description: All endpoints are protected using an authentication mechanism.
paths:
  /versions/{versionId}/ai_enrichment:
    post:
      summary: Create a new version of an enrichment
      parameters:
        - name: versionId
          in: path
          description: ID of the enrichment version to enrich
          required: true
          schema:
            type: string
            format: uuid4
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                enrichmentVersionMetadata:
                  $ref: "#/components/schemas/enrichmentVersionMetadata"
                multipleChoiceQuestions:
                  $ref: "#/components/schemas/multipleChoiceQuestions"
                taskId:
                  type: string
                  format: uuid4
                failureCause:
                  type: string
                status:
                  type: string
                  enum:
                    - OK
                    - KO
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: binary
                    description: Initial version ID
                  status:
                    type: string
                    enum:
                      - OK
                      - KO
        '400':
          description: Bad parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: User is not authenticated
        '403':
          description: User is not allowed to access this resource
        '404':
          description: No enrichment with given ID
    
  /enrichments/job/ai_enrichment/oldest:
    get:
      summary: Enable a user to list, with pagination, all of his own created enrichment
      parameters:
        - name: taskId
          in: query
          required: true
          schema:
            type: string
            format: uuid4
            description: A generated task id to track the request
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  enrichmentVersionId:
                    type: string
                    format: uuid4
                  mediaTypes:
                    type: array
                    items:
                      type: string
                  disciplines:
                    type: array
                    items:
                      type: string
                  transcript:
                    $ref: "#/components/schemas/transcript"
        '400':
          description: Bad parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: User is not authenticated
        '403':
          description: Not allowed (not connected as transcription worker)
        '404':
          description: No transcription job available currently
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    enrichmentVersionMetadata:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        topics:
          type: array
          items:
            type: string
        discipline:
          type: string
        mediaType:
          type: string
    multipleChoiceQuestions:
      type: array
      items:
        type: object
        properties:
          question:
            type: string
          explanation:
            type: string
          choices:
            type: object
            properties:
              optionText:
                type: string
              isCorrectAnswer:
                type: boolean
    transcript:
      type: object
      properties:
        originalFilename:
          type: string
        language:
          type: string
        sentences:
          type: array
          items:
            type: object
            properties:
              is_transient:
                type: boolean
              no_speech_prob:
                type: number
              start:
                type: number
              end:
                type: number
              text:
                type: string
        text:
          type: string
    ErrorResponse:
      type: object
      properties: 
        status: 
          type: string
          description: KO
        errors: 
          type: array
          items: 
            type: string
          description: Error messages
security:
  - bearerAuth: []