openapi: 3.0.3
info:
  title: Swagger Aristote - OpenAPI 3.0
  version: 0.0.1
  description: All endpoints are protected using an authentication mechanism.
paths:
  /enrichments/{enrichmentId}/versions/initial/transcript:
    post:
      summary: Create a new version of an enrichment
      parameters:
        - name: enrichmentId
          in: path
          description: ID of the enrichment to get
          required: true
          schema:
            type: string
            format: uuid4
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                transcript:
                  type: string
                  format: binary
                  description: File containing transcripts in subtitle format
                taskId:
                  type: string
                  format: uuid4
                failureCause:
                  type: string
                status:
                  type: string
                  enum:
                    - OK
                    - KO
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: binary
                    description: Initial version ID
                  status:
                    type: string
                    enum:
                      - OK
                      - KO
        '400':
          description: Bad parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: User is not authenticated
        '403':
          description: User is not allowed to access this resource
        '404':
          description: No enrichment with given ID
    
  /enrichments/transcription/job/oldest:
    get:
      summary: Enable a user to list, with pagination, all of his own created enrichment
      parameters:
        - name: taskId
          in: query
          required: true
          schema:
            type: string
            format: uuid4
            description: A generated task id to track the request
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  enrichmentId:
                    type: string
                    format: uuid4
                  mediaTemporaryUrl:
                    type: string
        '400':
          description: Bad parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: User is not authenticated
        '403':
          description: Not allowed (not connected as transcription worker)
        '404':
          description: No transcription job available currently
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorResponse:
      type: object
      properties: 
        status: 
          type: string
          description: KO
        errors: 
          type: array
          items: 
            type: string
          description: Error messages
security:
  - bearerAuth: []